// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: cosmos/msg/v1/msg.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
export namespace cosmos.msg.v1 { }
