// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.28.3
 * source: gogoproto/gogo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
export namespace gogoproto { }
