// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: realionetwork/asset/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_2 from "./params";
import * as dependency_3 from "./token";
import * as pb_1 from "google-protobuf";
export namespace realionetwork.asset.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            params?: dependency_2.realionetwork.asset.v1.Params;
            tokens?: dependency_3.realionetwork.asset.v1.Token[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("tokens" in data && data.tokens != undefined) {
                    this.tokens = data.tokens;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.realionetwork.asset.v1.Params, 1) as dependency_2.realionetwork.asset.v1.Params;
        }
        set params(value: dependency_2.realionetwork.asset.v1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_params() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get tokens() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_3.realionetwork.asset.v1.Token, 2) as dependency_3.realionetwork.asset.v1.Token[];
        }
        set tokens(value: dependency_3.realionetwork.asset.v1.Token[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.realionetwork.asset.v1.Params.prototype.toObject>;
            tokens?: ReturnType<typeof dependency_3.realionetwork.asset.v1.Token.prototype.toObject>[];
        }): GenesisState {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.realionetwork.asset.v1.Params.fromObject(data.params);
            }
            if (data.tokens != null) {
                message.tokens = data.tokens.map(item => dependency_3.realionetwork.asset.v1.Token.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.realionetwork.asset.v1.Params.prototype.toObject>;
                tokens?: ReturnType<typeof dependency_3.realionetwork.asset.v1.Token.prototype.toObject>[];
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.tokens != null) {
                data.tokens = this.tokens.map((item: dependency_3.realionetwork.asset.v1.Token) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_params)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (this.tokens.length)
                writer.writeRepeatedMessage(2, this.tokens, (item: dependency_3.realionetwork.asset.v1.Token) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.realionetwork.asset.v1.Params.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.tokens, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_3.realionetwork.asset.v1.Token.deserialize(reader), dependency_3.realionetwork.asset.v1.Token));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
