// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: realionetwork/asset/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_2 from "./params";
import * as pb_1 from "google-protobuf";
export namespace realionetwork.asset.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            params?: dependency_2.realionetwork.asset.v1.Params;
            port_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("port_id" in data && data.port_id != undefined) {
                    this.port_id = data.port_id;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.realionetwork.asset.v1.Params, 1) as dependency_2.realionetwork.asset.v1.Params;
        }
        set params(value: dependency_2.realionetwork.asset.v1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get port_id() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set port_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.realionetwork.asset.v1.Params.prototype.toObject>;
            port_id?: string;
        }): GenesisState {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.realionetwork.asset.v1.Params.fromObject(data.params);
            }
            if (data.port_id != null) {
                message.port_id = data.port_id;
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.realionetwork.asset.v1.Params.prototype.toObject>;
                port_id?: string;
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.port_id != null) {
                data.port_id = this.port_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.params !== undefined)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (typeof this.port_id === "string" && this.port_id.length)
                writer.writeString(2, this.port_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.realionetwork.asset.v1.Params.deserialize(reader));
                        break;
                    case 2:
                        message.port_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
