// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: realionetwork/asset/v1/tx.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace realionetwork.asset.v1 {
    export class MsgCreateToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creator?: string;
            name?: string;
            symbol?: string;
            total?: number;
            decimals?: number;
            authorizationRequired?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creator" in data && data.creator != undefined) {
                    this.creator = data.creator;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("total" in data && data.total != undefined) {
                    this.total = data.total;
                }
                if ("decimals" in data && data.decimals != undefined) {
                    this.decimals = data.decimals;
                }
                if ("authorizationRequired" in data && data.authorizationRequired != undefined) {
                    this.authorizationRequired = data.authorizationRequired;
                }
            }
        }
        get creator() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set creator(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get symbol() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get total() {
            return pb_1.Message.getField(this, 4) as number;
        }
        set total(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get decimals() {
            return pb_1.Message.getField(this, 5) as number;
        }
        set decimals(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get authorizationRequired() {
            return pb_1.Message.getField(this, 6) as boolean;
        }
        set authorizationRequired(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            creator?: string;
            name?: string;
            symbol?: string;
            total?: number;
            decimals?: number;
            authorizationRequired?: boolean;
        }): MsgCreateToken {
            const message = new MsgCreateToken({});
            if (data.creator != null) {
                message.creator = data.creator;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.total != null) {
                message.total = data.total;
            }
            if (data.decimals != null) {
                message.decimals = data.decimals;
            }
            if (data.authorizationRequired != null) {
                message.authorizationRequired = data.authorizationRequired;
            }
            return message;
        }
        toObject() {
            const data: {
                creator?: string;
                name?: string;
                symbol?: string;
                total?: number;
                decimals?: number;
                authorizationRequired?: boolean;
            } = {};
            if (this.creator != null) {
                data.creator = this.creator;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.total != null) {
                data.total = this.total;
            }
            if (this.decimals != null) {
                data.decimals = this.decimals;
            }
            if (this.authorizationRequired != null) {
                data.authorizationRequired = this.authorizationRequired;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.creator === "string" && this.creator.length)
                writer.writeString(1, this.creator);
            if (typeof this.name === "string" && this.name.length)
                writer.writeString(2, this.name);
            if (typeof this.symbol === "string" && this.symbol.length)
                writer.writeString(3, this.symbol);
            if (this.total !== undefined)
                writer.writeInt64(4, this.total);
            if (this.decimals !== undefined)
                writer.writeInt64(5, this.decimals);
            if (this.authorizationRequired !== undefined)
                writer.writeBool(6, this.authorizationRequired);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCreateToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCreateToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creator = reader.readString();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.symbol = reader.readString();
                        break;
                    case 4:
                        message.total = reader.readInt64();
                        break;
                    case 5:
                        message.decimals = reader.readInt64();
                        break;
                    case 6:
                        message.authorizationRequired = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCreateToken {
            return MsgCreateToken.deserialize(bytes);
        }
    }
    export class MsgCreateTokenResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgCreateTokenResponse {
            const message = new MsgCreateTokenResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCreateTokenResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCreateTokenResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCreateTokenResponse {
            return MsgCreateTokenResponse.deserialize(bytes);
        }
    }
    export class MsgUpdateToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creator?: string;
            symbol?: string;
            authorizationRequired?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creator" in data && data.creator != undefined) {
                    this.creator = data.creator;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("authorizationRequired" in data && data.authorizationRequired != undefined) {
                    this.authorizationRequired = data.authorizationRequired;
                }
            }
        }
        get creator() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set creator(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get symbol() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get authorizationRequired() {
            return pb_1.Message.getField(this, 3) as boolean;
        }
        set authorizationRequired(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            creator?: string;
            symbol?: string;
            authorizationRequired?: boolean;
        }): MsgUpdateToken {
            const message = new MsgUpdateToken({});
            if (data.creator != null) {
                message.creator = data.creator;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.authorizationRequired != null) {
                message.authorizationRequired = data.authorizationRequired;
            }
            return message;
        }
        toObject() {
            const data: {
                creator?: string;
                symbol?: string;
                authorizationRequired?: boolean;
            } = {};
            if (this.creator != null) {
                data.creator = this.creator;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.authorizationRequired != null) {
                data.authorizationRequired = this.authorizationRequired;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.creator === "string" && this.creator.length)
                writer.writeString(1, this.creator);
            if (typeof this.symbol === "string" && this.symbol.length)
                writer.writeString(2, this.symbol);
            if (this.authorizationRequired !== undefined)
                writer.writeBool(3, this.authorizationRequired);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUpdateToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUpdateToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creator = reader.readString();
                        break;
                    case 2:
                        message.symbol = reader.readString();
                        break;
                    case 3:
                        message.authorizationRequired = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUpdateToken {
            return MsgUpdateToken.deserialize(bytes);
        }
    }
    export class MsgUpdateTokenResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgUpdateTokenResponse {
            const message = new MsgUpdateTokenResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUpdateTokenResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUpdateTokenResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUpdateTokenResponse {
            return MsgUpdateTokenResponse.deserialize(bytes);
        }
    }
    export class MsgAuthorizeAddress extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creator?: string;
            symbol?: string;
            address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creator" in data && data.creator != undefined) {
                    this.creator = data.creator;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("address" in data && data.address != undefined) {
                    this.address = data.address;
                }
            }
        }
        get creator() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set creator(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get symbol() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get address() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            creator?: string;
            symbol?: string;
            address?: string;
        }): MsgAuthorizeAddress {
            const message = new MsgAuthorizeAddress({});
            if (data.creator != null) {
                message.creator = data.creator;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.address != null) {
                message.address = data.address;
            }
            return message;
        }
        toObject() {
            const data: {
                creator?: string;
                symbol?: string;
                address?: string;
            } = {};
            if (this.creator != null) {
                data.creator = this.creator;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.address != null) {
                data.address = this.address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.creator === "string" && this.creator.length)
                writer.writeString(1, this.creator);
            if (typeof this.symbol === "string" && this.symbol.length)
                writer.writeString(2, this.symbol);
            if (typeof this.address === "string" && this.address.length)
                writer.writeString(3, this.address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgAuthorizeAddress {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgAuthorizeAddress();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creator = reader.readString();
                        break;
                    case 2:
                        message.symbol = reader.readString();
                        break;
                    case 3:
                        message.address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgAuthorizeAddress {
            return MsgAuthorizeAddress.deserialize(bytes);
        }
    }
    export class MsgAuthorizeAddressResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgAuthorizeAddressResponse {
            const message = new MsgAuthorizeAddressResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgAuthorizeAddressResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgAuthorizeAddressResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgAuthorizeAddressResponse {
            return MsgAuthorizeAddressResponse.deserialize(bytes);
        }
    }
    export class MsgUnAuthorizeAddress extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creator?: string;
            symbol?: string;
            address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creator" in data && data.creator != undefined) {
                    this.creator = data.creator;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("address" in data && data.address != undefined) {
                    this.address = data.address;
                }
            }
        }
        get creator() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set creator(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get symbol() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get address() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            creator?: string;
            symbol?: string;
            address?: string;
        }): MsgUnAuthorizeAddress {
            const message = new MsgUnAuthorizeAddress({});
            if (data.creator != null) {
                message.creator = data.creator;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.address != null) {
                message.address = data.address;
            }
            return message;
        }
        toObject() {
            const data: {
                creator?: string;
                symbol?: string;
                address?: string;
            } = {};
            if (this.creator != null) {
                data.creator = this.creator;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.address != null) {
                data.address = this.address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.creator === "string" && this.creator.length)
                writer.writeString(1, this.creator);
            if (typeof this.symbol === "string" && this.symbol.length)
                writer.writeString(2, this.symbol);
            if (typeof this.address === "string" && this.address.length)
                writer.writeString(3, this.address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUnAuthorizeAddress {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUnAuthorizeAddress();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creator = reader.readString();
                        break;
                    case 2:
                        message.symbol = reader.readString();
                        break;
                    case 3:
                        message.address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUnAuthorizeAddress {
            return MsgUnAuthorizeAddress.deserialize(bytes);
        }
    }
    export class MsgUnAuthorizeAddressResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgUnAuthorizeAddressResponse {
            const message = new MsgUnAuthorizeAddressResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUnAuthorizeAddressResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUnAuthorizeAddressResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUnAuthorizeAddressResponse {
            return MsgUnAuthorizeAddressResponse.deserialize(bytes);
        }
    }
    export class MsgTransferToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creator?: string;
            symbol?: string;
            from?: string;
            to?: string;
            amount?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creator" in data && data.creator != undefined) {
                    this.creator = data.creator;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("from" in data && data.from != undefined) {
                    this.from = data.from;
                }
                if ("to" in data && data.to != undefined) {
                    this.to = data.to;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get creator() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set creator(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get symbol() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get from() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set from(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get to() {
            return pb_1.Message.getField(this, 4) as string;
        }
        set to(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get amount() {
            return pb_1.Message.getField(this, 5) as number;
        }
        set amount(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            creator?: string;
            symbol?: string;
            from?: string;
            to?: string;
            amount?: number;
        }): MsgTransferToken {
            const message = new MsgTransferToken({});
            if (data.creator != null) {
                message.creator = data.creator;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.from != null) {
                message.from = data.from;
            }
            if (data.to != null) {
                message.to = data.to;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            return message;
        }
        toObject() {
            const data: {
                creator?: string;
                symbol?: string;
                from?: string;
                to?: string;
                amount?: number;
            } = {};
            if (this.creator != null) {
                data.creator = this.creator;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.from != null) {
                data.from = this.from;
            }
            if (this.to != null) {
                data.to = this.to;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.creator === "string" && this.creator.length)
                writer.writeString(1, this.creator);
            if (typeof this.symbol === "string" && this.symbol.length)
                writer.writeString(2, this.symbol);
            if (typeof this.from === "string" && this.from.length)
                writer.writeString(3, this.from);
            if (typeof this.to === "string" && this.to.length)
                writer.writeString(4, this.to);
            if (this.amount !== undefined)
                writer.writeInt64(5, this.amount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgTransferToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgTransferToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creator = reader.readString();
                        break;
                    case 2:
                        message.symbol = reader.readString();
                        break;
                    case 3:
                        message.from = reader.readString();
                        break;
                    case 4:
                        message.to = reader.readString();
                        break;
                    case 5:
                        message.amount = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgTransferToken {
            return MsgTransferToken.deserialize(bytes);
        }
    }
    export class MsgTransferTokenResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgTransferTokenResponse {
            const message = new MsgTransferTokenResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgTransferTokenResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgTransferTokenResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgTransferTokenResponse {
            return MsgTransferTokenResponse.deserialize(bytes);
        }
    }
}
